const Images = {
  zwilt: new URL("./zwilt-tba-1-01 2.png", import.meta.url).href,
  stripe: new URL("./stripe.png", import.meta.url).href,
  rectangle: new URL("./rectangle.png", import.meta.url).href,
  shopify: new URL("./shopify.png", import.meta.url).href,
  magento: new URL("./magento.png", import.meta.url).href,
  data: new URL("./data.png", import.meta.url).href,
  webflow: new URL("./webflow.png", import.meta.url).href,
  dot: new URL("./dot.png", import.meta.url).href,
  rightZwilt: new URL("./right-zwilt.png", import.meta.url).href,
  leftZwilt: new URL("./left-zwilt.png", import.meta.url).href,
  figma: new URL("./figma.png", import.meta.url).href,
  photoShop: new URL("./photoshop.png", import.meta.url).href,
  ai: new URL("./ai.png", import.meta.url).href,
  unreal: new URL("./unreal.png", import.meta.url).href,
  cinema: new URL("./cinema.png", import.meta.url).href,
  medal: new URL("./medal.png", import.meta.url).href,
  category: new URL("./category.png", import.meta.url).href,
  profile: new URL("./profile.png", import.meta.url).href,
  halfTopBlue: new URL("./half-top-blue.png", import.meta.url).href,
  halfBottomBlue: new URL("./half-btm-blue.png", import.meta.url).href,
  footerRect: new URL("./footer-rectangle.png", import.meta.url).href,
  zwiltDown: new URL("./zwilt-down.png", import.meta.url).href,
  footerZwilt: new URL("./footer-logo.png", import.meta.url).href,
  yellowZwilt: new URL("./zwilt-yellow.png", import.meta.url).href,
  quote: new URL("./quote.png", import.meta.url).href,
  groove: new URL("./groove.png", import.meta.url).href,
  jason: new URL("./jason.png", import.meta.url).href,
  groovehq: new URL("./groovehq.png", import.meta.url).href,
  play: new URL("./play.png", import.meta.url).href,
  bluePlay: new URL("./blue-play.png", import.meta.url).href,
  frm: new URL("./frm.png", import.meta.url).href,
  risk: new URL("./risk.png", import.meta.url).href,
  book: new URL("./book.png", import.meta.url).href,
  loop: new URL("./loop.png", import.meta.url).href,
  ariana: new URL("./ariana.png", import.meta.url).href,
  menGroup: new URL("./men-group.png", import.meta.url).href,
  note: new URL("./note.png", import.meta.url).href,
  tenTimes: new URL("./10x.png", import.meta.url).href,

};

export default Images;
