const Images = {
  logo: new URL("./logo.png", import.meta.url).href,
  zwilt: new URL("./zwilt-tba-1-01 2.png", import.meta.url).href,
  inputIcon: new URL("./input-icon.png", import.meta.url).href,
  union: new URL("./union.png", import.meta.url).href,
  rectangle: new URL("./rectangle.png", import.meta.url).href,
  shopify: new URL("./shopify.png", import.meta.url).href,
  magento: new URL("./magento.png", import.meta.url).href,
  data: new URL("./data.png", import.meta.url).href,
  webflow: new URL("./webflow.png", import.meta.url).href,
  dot: new URL("./dot.png", import.meta.url).href,
  rightZwilt: new URL("./right-zwilt.png", import.meta.url).href,
  leftZwilt: new URL("./left-zwilt.png", import.meta.url).href,
  figma: new URL("./figma.png", import.meta.url).href,
  photoShop: new URL("./photoshop.png", import.meta.url).href,
  ai: new URL("./ai.png", import.meta.url).href,
  unreal: new URL("./unreal.png", import.meta.url).href,
  cinema: new URL("./cinema.png", import.meta.url).href,
  medal: new URL("./medal.png", import.meta.url).href,
  category: new URL("./category.png", import.meta.url).href,
  profile: new URL("./profile.png", import.meta.url).href,
  roundZwilt: new URL("./round-zwilt.png", import.meta.url).href,
  footerBg: new URL("./footer-bg.png", import.meta.url).href,
  footerRect: new URL("./footer-rectangle.png", import.meta.url).href,
  zwiltDown: new URL("./zwilt-down.png", import.meta.url).href,
  footerZwilt: new URL("./footer-logo.png", import.meta.url).href,
  yellowZwilt: new URL("./zwilt-yellow.png", import.meta.url).href,
};

export default Images;
